name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.d2e2dd144f573ad4493ec8df6e009af248ab328b }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
