name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.f7b5c0cd0ac71eb2beafd03b1bf7193b9e814989 }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
